### ISSUE TITLE
1.11 is not published?

### ISSUE THREAD

**Issue by kevdowney** [MichaelTamm/junit-toolbox#20]
I see 1.11-SNAPSHOT but not 1.11 version as mentioned in README docs equivalent to 2.3. Is 1.11 ready?

**Comment by MichaelTamm** [comment]
I did not publish 1.11 yet, because I thought Java 6 support is not needed anymore. Well, this issue tells me, I was wrong. ;) I'm sorry for the incorrect README. :( I hope I will have time to publish the missing version in the next days ...

**Comment by kevdowney** [comment]
Thanks. Can you clarify if 1.11 is for Java 6 & 7?

**Comment by MichaelTamm** [comment]
I'm sorry, that it took so long, but I finally released version 1.11, which is for Java 6 and for Java 7.

**Comment by kevdowney** [comment]
Thanks.
