### ISSUE TITLE
@SuiteClasses takes class objects and not Strings

### ISSUE THREAD

**Issue by markthegrea** [MichaelTamm/junit-toolbox#24]
Am I out of my mind or what?  The code for SuiteClasses takes an array of classes but all the documentation shows Strings.  Something is big time wrong!  I am using 2.4 (latest).

@SuiteClasses("**/*Test.class")

@Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    @Inherited
    public @interface SuiteClasses {
        /**
         * @return the classes to be run
         */
        public Class<?>[] value();
    }

**Comment by MichaelTamm** [comment]
Sorry for the confusion, please let me clarify: There are two different annotations `@SuiteClasses`:

First, there is the one from JUnit 4 defined in the Junit 4 runner class `org.junit.runners.Suite`, which indeed takes an array of classes as value.

But I didn't like to specify all test classes when using the `Suite` runner, therefore I decided to write the `WildcardPatternSuite`. To use it, you should use the `@SuiteClasses` annotation defined in the package `com.googlecode.junittoolbox`, which takes an array of strings as value.

Maybe it wasn't such a good idea, to give that annotation the exact same name.

By the way, the `WildcardPatternSuite` (as well as the `ParallelSuite`) runner support both annotations: `org.junit.runners.Suite.SuiteClasses` and `com.googlecode.junittoolbox.SuiteClasses`

**Comment by markthegrea** [comment]
Got it.  Thanks!  Maybe this post will help out others. 

Great software by the way!
